import { ISupplier } from './shared/models/searchSuppliers/ISearchSuppliers';

export const SUPPLIERS: ISupplier[] = [{
    "CompanyId": 6675484,
    "AsiNumber": "23218",
    "CompanyName": "The Mug Factory",
    "Address1": "39 Secam Street",
    //"Address2": "Unit 4",
    "City": "Mansfield",
    "StateCode": "QLD",
    "PostalCode": "4122",
    "CountryCode": "AUS",
    "PhoneNumber": "011(61)7-3349-6980",
    "EmailAddress": "sales@themugfactory.com.au",
    "MemberTypeCode": "ANZS",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    //"County": "",
    //"SupplierLevel": 0
}, {
    "CompanyId": 105229,
    "AsiNumber": "270990",
    "CompanyName": "Mig Mug",
    "Address1": "29 Pokahoe Dr",
    //"Address2": "",    
    "City": "Sleepy Hollow",
    "StateCode": "NY",
    "PostalCode": "10591-1104",
    //"County": "Westchester",
    "CountryCode": "USA",
    "PhoneNumber": "(914) 631-3375",
    "EmailAddress": "migmug@aol.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    //"SupplierLevel": 0
}, {
    "CompanyId": 7910033,
    "AsiNumber": "278111",
    "CompanyName": "Mugs Across America, Inc",
    "Address1": "128 Viking Way",
    //"Address2": "Unit 4",    
    "City": "Naples",
    "StateCode": "FL",
    "PostalCode": "34110",
    "CountryCode": "USA",
    "PhoneNumber": "(269) 978-3638",
    "EmailAddress": "mugsacrossamerica@yahoo.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    // "County": "",
    // "SupplierLevel": 0    
}, {
    "CompanyId": 6387495,
    "AsiNumber": "530126",
    "CompanyName": "Mugshots Custom Printing, LLC",
    "Address1": "72 16th Ave SW",
    //"Address2": "Unit 4",  
    "City": "Cedar Rapids",
    "StateCode": "IA",
    "PostalCode": "52404",
    "CountryCode": "USA",
    "PhoneNumber": "(319) 390-2043",
    "EmailAddress": "mugshots@outlook.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    //"County": "",
    //"SupplierLevel": 0    
}, {
    "CompanyId": 6725608,
    "AsiNumber": "89971",
    "CompanyName": "Stuff A Mug",
    "Address1": "831-38 Route 10 East Unit 275",
    //"Address2": "Unit 4",  
    "City": "Whippany",
    "StateCode": "NJ",
    "PostalCode": "07981",
    //"County": "Morris",
    "CountryCode": "USA",
    "PhoneNumber": "(973) 695-1881",
    "EmailAddress": "orders@stuffamug.com",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": true
}, {
    "CompanyId": 832611,
    "AsiNumber": "181638",
    "CompanyName": "Docuplex",
    "Address1": "630 N Pennsylvania Ave",
    "City": "Wichita",
    "StateCode": "KS",
    "PostalCode": "67214-4157",
    "CountryCode": "USA",
    "PhoneNumber": "(316) 262-2662",
    "EmailAddress": "charter@docuplex.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 7952405,
    "AsiNumber": "18360",
    "CompanyName": "Cupcake3@cake.Com",
    "Address1": "5fdsf",
    "City": "Fds",
    "StateCode": "AK",
    "PostalCode": "43",
    "CountryCode": "USA",
    "PhoneNumber": "(454) 545-4545",
    "MemberTypeCode": "SPLR",
    "EmailAddress": "charter@docuplex.com",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 540177,
    "AsiNumber": "374521",
    "CompanyName": "Acuprint",
    "Address1": "5920 Bowcroft St",
    "City": "Los Angeles",
    "StateCode": "CA",
    "PostalCode": "90016-4302",
    //"County": "Los Angeles",
    "CountryCode": "USA",
    "PhoneNumber": "(310) 280-6060",
    "EmailAddress": "fletch@acuprint.net",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 942,
    "AsiNumber": "45800",
    "CompanyName": "Color Cup Corp",
    "Address1": "PO Box 1018",
    "City": "Sanger",
    "StateCode": "TX",
    "PostalCode": "76266-1018",
    //"County": "Denton",
    "CountryCode": "USA",
    "PhoneNumber": "(940) 458-4109",
    "EmailAddress": "crystal@colorcup.com",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 7027108,
    "AsiNumber": "46814",
    "CompanyName": "Covocup",
    "Address1": "6212 29th St E",
    "City": "Bradenton",
    "StateCode": "FL",
    "PostalCode": "34203-5304",
   // "County": "Manatee",
    "CountryCode": "USA",
    "PhoneNumber": "(855) 204-5106",
    "EmailAddress": "sales@covocup.com",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 953072,
    "AsiNumber": "47874",
    "CompanyName": "Cup Ads LLC",
    "Address1": "2 Central Ave",
    "City": "Caldwell",
    "StateCode": "NJ",
    "PostalCode": "07006-4802",
    //"County": "Essex",
    "CountryCode": "USA",
    "PhoneNumber": "(973) 521-7089",
    "EmailAddress": "Info@cupads.com",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 7952401,
    "AsiNumber": "47876",
    "CompanyName": "Cupcake1@cake.Com",
    "EmailAddress": "charter@docuplex.com",
    "Address1": "5fds",
    "City": "Fds",
    "StateCode": "AZ",
    "PostalCode": "432",
    "CountryCode": "USA",
    "PhoneNumber": "(454) 545-4545",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 7952403,
    "AsiNumber": "47877",
    "CompanyName": "Cupcakes2@cake.Com",
    "Address1": "4fds",
    "City": "Fds",
    "StateCode": "AK",
    "PostalCode": "43",
    "CountryCode": "USA",
    "PhoneNumber": "(454) 545-4545",
    "MemberTypeCode": "SPLR",
    "EmailAddress": "charter@docuplex.com",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 309456,
    "AsiNumber": "490715",
    "CompanyName": "Proforma Docuprint Services",
    "Address1": "2106 Crossgate Dr",
    "City": "Crofton",
    "StateCode": "MD",
    "PostalCode": "21114-2906",
    //"County": "Anne Arundel",
    "CountryCode": "USA",
    "PhoneNumber": "(301) 858-0704",
    "EmailAddress": "tim.michienzi@proforma.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 7285,
    "AsiNumber": "49675",
    "CompanyName": "Dickies Occupational Wear",
    "Address1": "509 W Vickery Blvd",
    "City": "Fort Worth",
    "StateCode": "TX",
    "PostalCode": "76104-1110",
    //"County": "Tarrant",
    "CountryCode": "USA",
    "PhoneNumber": "(800) 336-7201",
    "EmailAddress": "Industrialorders@dickies.com",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": true
}, {
    "CompanyId": 1299,
    "AsiNumber": "51730",
    "CompanyName": "Americas Cups Worldwide",
    "Address1": "357 S Arrowhead",
    "City": "San Bernardino",
    "StateCode": "CA",
    "PostalCode": "92408",
    //"County": "San Bernardino",
    "CountryCode": "USA",
    "PhoneNumber": "(909) 888-0502",
    "EmailAddress": "americascups@att.net",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": true
}, {
    "CompanyId": 3229920,
    "AsiNumber": "529556",
    "CompanyName": "Docuprint",
    "Address1": "147 Edinburg Ct",
    "City": "Lake Mary",
    "StateCode": "FL",
    "PostalCode": "32746-6219",
    //"County": "Seminole",
    "EmailAddress": "charter@docuplex.com",
    "CountryCode": "USA",
    "PhoneNumber": "(407) 718-4359",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 1034840,
    "AsiNumber": "560051",
    "CompanyName": "Accuprint, Inc.",
    "Address1": "2414 Palumbo Dr",
    //"Address2": "",
    //"Address3": "",
    //"Address4": "",
    "City": "Lexington",
    "StateCode": "KY",
    "PostalCode": "40509-1117",
    "CountryCode": "USA",
    "PhoneNumber": "(859) 268-8844",
    "EmailAddress": "mike@accuprint.us",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 7887070,
    "AsiNumber": "59492",
    "CompanyName": "Handle This Cup",
    "Address1": "111 38th Ave",
    "City": "Greeley",
    "StateCode": "CO",
    "PostalCode": "80634-1117",
    //"County": "Weld",
    "CountryCode": "USA",
    "PhoneNumber": "(970) 330-5087",
    "EmailAddress": "ron@handlethiscup.com",
    "MemberTypeCode": "SPLR",
    //"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}, {
    "CompanyId": 3276,
    "AsiNumber": "88200",
    "CompanyName": "TK Cups-Sorg's",
    "Address1": "750 Crawford St",
    "City": "Fitchburg",
    "StateCode": "MA",
    "PostalCode": "01420-6814",
    //"County": "Worcester",
    "CountryCode": "USA",
    "PhoneNumber": "(800) 337-2750",
    "EmailAddress": "info@tkcups-sorgs.com",
    "MemberTypeCode": "SPLR",
    ///"SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false
}
];