import { ISupplier } from './shared/models/searchSuppliers/ISearchSuppliers';

export const SUPPLIERS: ISupplier[] = [{
    "CompanyId": 6675484,
    "AsiNumber": "23218",
    "CompanyName": "The Mug Factory",
    "Address1": "39 Secam Street",
    "Address2": "Unit 4",
    "City": "Mansfield",
    "StateCode": "QLD",
    "PostalCode": "4122",
    "CountryCode": "AUS",
    "PhoneNumber": "011(61)7-3349-6980",
    "EmailAddress": "sales@themugfactory.com.au",
    "MemberTypeCode": "ANZS",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    "County": "",
    "SupplierLevel": 0
}, {
    "CompanyId": 105229,
    "AsiNumber": "270990",
    "CompanyName": "Mig Mug",
    "Address1": "29 Pokahoe Dr",
    "Address2": "",    
    "City": "Sleepy Hollow",
    "StateCode": "NY",
    "PostalCode": "10591-1104",
    "County": "Westchester",
    "CountryCode": "USA",
    "PhoneNumber": "(914) 631-3375",
    "EmailAddress": "migmug@aol.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    "SupplierLevel": 0
}, {
    "CompanyId": 7910033,
    "AsiNumber": "278111",
    "CompanyName": "Mugs Across America, Inc",
    "Address1": "128 Viking Way",
    "Address2": "Unit 4",    
    "City": "Naples",
    "StateCode": "FL",
    "PostalCode": "34110",
    "CountryCode": "USA",
    "PhoneNumber": "(269) 978-3638",
    "EmailAddress": "mugsacrossamerica@yahoo.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    "County": "",
    "SupplierLevel": 0    
}, {
    "CompanyId": 6387495,
    "AsiNumber": "530126",
    "CompanyName": "Mugshots Custom Printing, LLC",
    "Address1": "72 16th Ave SW",
    "Address2": "Unit 4",  
    "City": "Cedar Rapids",
    "StateCode": "IA",
    "PostalCode": "52404",
    "CountryCode": "USA",
    "PhoneNumber": "(319) 390-2043",
    "EmailAddress": "mugshots@outlook.com",
    "MemberTypeCode": "DIST",
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": false,
    "County": "",
    "SupplierLevel": 0    
}, {
    "CompanyId": 6725608,
    "AsiNumber": "89971",
    "CompanyName": "Stuff A Mug",
    "Address1": "831-38 Route 10 East Unit 275",
    "Address2": "Unit 4",  
    "City": "Whippany",
    "StateCode": "NJ",
    "PostalCode": "07981",
    "County": "Morris",
    "CountryCode": "USA",
    "PhoneNumber": "(973) 695-1881",
    "EmailAddress": "orders@stuffamug.com",
    "MemberTypeCode": "SPLR",
    "SupplierLevel": 9,
    "Premier": "No",
    "Replink": "NO",
    "Mapped": "No",
    "TLC": "No",
    "Spotlight": "No",
    "API": "No",
    "HasNotes": true
}
];